### ISSUE TITLE
Great job on taking them down.

### ISSUE THREAD

**Issue by netzeroo** [holo-gfx/mangadex#70]
Hopefully this can let the community look into using a more secure option, on the longterm we all benefit from this.

**Comment by ObserverOfTime** [comment]
[It doesn't look like it will.](https://www.reddit.com/r/mangadex/comments/m93sk1/mangadex_hacked_yet_again/)

**Comment by Kadantte** [comment]
> [It doesn't look like the community cares about security.](https://www.reddit.com/r/mangadex/comments/m93sk1/mangadex_hacked_yet_again/)

He is talking bato.to the same website that shares the same user database with Mangadex 🤦‍♂️

**Comment by Kadantte** [comment]
> [It doesn't look like the community cares about security.](https://www.reddit.com/r/mangadex/comments/m93sk1/mangadex_hacked_yet_again/)

@ObserverOfTime  I like your MangAdventure I'm hosting my own version locally!

**Comment by ObserverOfTime** [comment]
@Kadantte That's great! If you end up publishing the site, please send me the link.
