### ISSUE TITLE
Oh shit, is this the source code for actual mangadex?

### ISSUE THREAD

**Issue by JaneJeon** [holo-gfx/mangadex#72]
Not interested in hacking drama, but I love reading through websites’ source codes (idk it’s just a hobby of mine).

How recent-ish is this (in terms of date)? I haven’t been keeping up with mangadex’s “versions” so I have no idea what v3, v4, or v5 even means in practical terms

Edit: and I’m guessing the CVE has to do with session handling? Like https://github.com/holo-gfx/mangadex/blob/main/ajax/actions/auth.actions.req.php or https://github.com/holo-gfx/mangadex/blob/main/src/Model/Guard.php?

Man I’m just curious as hell now ahaha

**Comment by EisbarGFX** [comment]
The current code is, as far as we all can tell, recent to the order of a few weeks to as recent as possible. Also, in the other, more commented-in "issue" thread here, the user NetZeRoo ran a security check and posted an imgur of their results. You can look at the two CVE's found in that thread.

and as for what the versions are, it's to my knowledge just the names given to the different times they've re-written the code. v4 is the current one on the site, AKA the code in this repository. It was done in a matter of a few days after a v3 source code leak a long time ago, so is a massive mess of spaghetti. 
v5 is the re-work of mangadex's code in an attempt to fix the spaghetti. It's been in the works for a while, but this has forced the MD staff to accelerate it a little - as explained in their notice on the site.

**Comment by JaneJeon** [comment]
Thank you! I’ll take a look at the other thread as well :D

**Comment by Jendrej** [comment]
This code is v3, they are skipping v4 and v5 is the future rewrite.
